#!/bin/env node

// Usage:
//
// nickel-chrome [nb-workers]
//
// The default nb workers is 5.

const { version } = require('../package.json')
const scheduler = require('./scheduler')
const parseBody = require('./parseBody')
const log = require('./log')

const NB_WORKERS = parseInt(process.argv[2], 10) || 5

console.log(`
   ╔═══════════════════╗
   ║                   ║
   ║   NICKEL-CHROME   ║
   ║                   ║
   ╟───────────────────╢
   ║ ${version}             ║
   ╚═══════════════════╝
`)

scheduler.launchWorkers(NB_WORKERS)

require('./createServer')(async (req, res) => {
  try {
    log.log('Receiving request')
    const now = Date.now()
    const payload = await parseBody(req)
    const base64 = await scheduler.screenshot(payload)
    log.log(`Screenshot done in ${Date.now() - now}ms`)
    res.writeHead(200)
    res.end(base64)
  } catch (err) {
    log.error(err)
    res.writeHead(500)
    res.end('KO')
  }
})

async function onExit() {
  await scheduler.stopWorkers()
  process.exit()
}

process.on('exit', onExit)
process.on('SIGINT', onExit)
